insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHEE-S','Cheese','Pizza','Small',19.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHEE-M','Cheese','Pizza','Medium',24.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHEE-L','Cheese','Pizza','Large',29.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-PEPP-S','Pepperoni','Pizza','Small',20.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-PEPP-M','Pepperoni','Pizza','Medium',25.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-PEPP-L','Pepperoni','Pizza','Large',31.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-HAWA-S','Hawaiian','Pizza','Small',21.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-HAWA-M','Hawaiian','Pizza','Medium',26.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-HAWA-L','Hawaiian','Pizza','Large',32.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-DONA-S','Donair','Pizza','Small',23.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-DONA-M','Donair','Pizza','Medium',29.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-DONA-L','Donair','Pizza','Large',35.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-BBQC-S','BBQ Chicken','Pizza','Small',23.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-BBQC-M','BBQ Chicken','Pizza','Medium',29.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-BBQC-L','BBQ Chicken','Pizza','Large',35.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHBR-S','Chicken Bacon Ranch','Pizza','Small',23.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHBR-M','Chicken Bacon Ranch','Pizza','Medium',29.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('PIZZ-CHBR-L','Chicken Bacon Ranch','Pizza','Large',35.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('SIDE-GARL-R','Garlic Bread','Side','Regular',9.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('SIDE-CHIC-R','Chicken Wings','Side','Regular',10.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('SIDE-CAES-R','Caesar Salad','Side','Regular',10.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('DESS-CHBR-R','Chocolate Brownie','Dessert','Regular',8.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('DESS-CHCA-R','Cheesecake','Dessert','Regular',8.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-RPE','Pepsi','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-DPE','Diet Pepsi','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-7UP','7 Up','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-RBE','Root Beer','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-ICT','Iced Tea','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-GAL','Ginger Ale','Beverage','2L',3.99);
insert into items (sku,item_name,item_cat,item_size,item_price)values('BEVA-DRP','Dr Pepper','Beverage','2L',3.99);