insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Pizza dough ball  (8 pack)',2000,'grams',4.59);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Tomato sauce',4500,'grams',3.89);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Donair sauce',4500,'grams',4.99);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Ranch sauce',4500,'grams',4.99);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Mozzarella',2500,'grams',14.45);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Pepperoni',2500,'grams',23.22);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Ham',5000,'grams',32.45);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Pineapple',5000,'grams',6.43);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Donair meat',5000,'grams',35.72);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Onion',1000,'grams',4.97);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Tomatoes',1000,'grams',3.78);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Chicken',5000,'grams',31.25);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Bacon',5000,'grams',36.55);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Peppers',1000,'grams',3.45);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Garlic herb butter',3000,'grams',52.12);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Chicken wings',6000,'grams',65.83);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Romaine lettuce',7500,'grams',13.79);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Caesar dressing',3800,'grams',17.65);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Croutons',1250,'grams',5.25);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Chocolate brownie',2500,'grams',4.65);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Cheesecake',2500,'grams',4.65);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('BBQ sauce',4500,'grams',4.99);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('Parmesan',2500,'grams',14.65);
insert into ingredients(ing_name,ing_weight,ing_meas,ing_price) values('No Ingredients',0,'grams', 0);