insert into staff (first_name, last_name, position, hourly_rate) values ('Liam', 'Anderson', 'Prep chef',16.5);
insert into staff (first_name, last_name, position, hourly_rate) values ('Olivia', 'Johnson', 'Chef',21.25);
insert into staff (first_name, last_name, position, hourly_rate) values ('Ethan', 'Smith', 'Prep chef',16.5);
insert into staff (first_name, last_name, position, hourly_rate) values ('Ava', 'Brown', 'Chef',21.25);
insert into staff (first_name, last_name, position, hourly_rate) values ('Noah', 'Davis', 'Prep chef',16.5);
insert into staff (first_name, last_name, position, hourly_rate) values ('Emma', 'Taylor', 'Chef',21.25);
insert into staff (first_name, last_name, position, hourly_rate) values ('Mason', 'Miller', 'Prep chef',16.5);
insert into staff (first_name, last_name, position, hourly_rate) values ('Sophia', 'Wilson', 'Chef',21.25);
insert into staff (first_name, last_name, position, hourly_rate) values ('Logan', 'Moore', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Isabella', 'Martinez', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Aiden', 'Jackson', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Mia', 'White', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Lucas', 'Harris', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Amelia', 'Nelson', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Jackson', 'Garcia', 'Delivery driver',15);
insert into staff (first_name, last_name, position, hourly_rate) values ('Harper', 'Robinson', 'Delivery driver',15);